### ISSUE TITLE
build failing on musl libc

### ISSUE THREAD

**Issue by cz172638** [saulius/croaring-rs#76]
croaring-rs is failing on musl libc distributions like alpine (`podman run --rm -it alpine:3.15`)
steps:
```
apk add clang lld curl git openssh-client build-base protoc openssl3-dev llvm-dev && \
curl -q --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -qy && \
source $HOME/.cargo/env && \
git clone --recursive https://github.com/saulius/croaring-rs /croaring-rs && \
cd /croaring-rs/croaring-sys/ && \
RUST_BACKTRACE=full cargo build
```
backtrace:
```
   Compiling croaring-sys v0.5.1 (/croaring-rs/croaring-sys)
error: failed to run custom build command for `croaring-sys v0.5.1 (/croaring-rs/croaring-sys)`

Caused by:
  process didn't exit successfully: `/croaring-rs/target/debug/build/croaring-sys-c8f4e4f44dbf8fe6/build-script-build` (exit status: 101)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-musl")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-musl")
  CC_x86_64-unknown-linux-musl = None
  CC_x86_64_unknown_linux_musl = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-musl = None
  CFLAGS_x86_64_unknown_linux_musl = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/croaring-rs/target/debug/build/croaring-sys-fcf69fc1be8b5492/out/CRoaring/roaring.o" "-c" "CRoaring/roaring.c"
  exit status: 0
  AR_x86_64-unknown-linux-musl = None
  AR_x86_64_unknown_linux_musl = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/croaring-rs/target/debug/build/croaring-sys-fcf69fc1be8b5492/out/libroaring.a" "/croaring-rs/target/debug/build/croaring-sys-fcf69fc1be8b5492/out/CRoaring/roaring.o"
  exit status: 0
  running: "ar" "s" "/croaring-rs/target/debug/build/croaring-sys-fcf69fc1be8b5492/out/libroaring.a"
  exit status: 0
  cargo:rustc-link-lib=static=roaring
  cargo:rustc-link-search=native=/croaring-rs/target/debug/build/croaring-sys-fcf69fc1be8b5492/out

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib/libclang.so.12 could not be opened: Dynamic loading not supported"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2144:31
  stack backtrace:
     0:     0x7f715375ed1c - std::backtrace_rs::backtrace::libunwind::trace::hc1bc96ddb4426aa4
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:     0x7f715375ed1c - std::backtrace_rs::backtrace::trace_unsynchronized::h923980a653d66493
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x7f715375ed1c - std::sys_common::backtrace::_print_fmt::h9c757c85a437b931
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x7f715375ed1c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4daee6a3bf7c86e
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x7f71537998ec - core::fmt::write::hb92fcd00ba9c1ad2
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
     5:     0x7f715375a785 - std::io::Write::write_fmt::he1040163a0175759
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
     6:     0x7f71537609e0 - std::sys_common::backtrace::_print::h41aed1f85e85fe81
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x7f71537609e0 - std::sys_common::backtrace::print::h80502ae1de52b70b
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x7f71537609e0 - std::panicking::default_hook::{{closure}}::ha8bcafa5b9176f3f
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
     9:     0x7f7153760595 - std::panicking::default_hook::hfaee58ed0a065bec
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
    10:     0x7f7153761094 - std::panicking::rust_panic_with_hook::h8ce3328d937db5aa
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
    11:     0x7f7153760b70 - std::panicking::begin_panic_handler::{{closure}}::h1f2295b855ba5030
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
    12:     0x7f715375f1c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h17092a58b60b0566
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
    13:     0x7f7153760ad9 - rust_begin_unwind
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
    14:     0x7f71531d6631 - core::panicking::panic_fmt::hcf6bd03e382adeab
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
    15:     0x7f71531d6723 - core::result::unwrap_failed::h831f708977462148
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
    16:     0x7f71533055a3 - core::result::Result<T,E>::expect::hd3f8e832994fe1f2
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1258:23
    17:     0x7f715324736d - <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::__static_ref_initialize::h89ea8f15e31a9c42
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2144:13
    18:     0x7f715324736d - core::ops::function::FnOnce::call_once::h39b02bfd30e8e1bc
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
    19:     0x7f715327c8b7 - lazy_static::lazy::Lazy<T>::get::{{closure}}::h2e574b30351a1a1a
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:31:29
    20:     0x7f715327d57e - std::sync::once::Once::call_once::{{closure}}::hde3635e6eaafb54f
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sync/once.rs:262:41
    21:     0x7f71531d5858 - std::sync::once::Once::call_inner::hc80c2db9bc163fc9
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sync/once.rs:419:21
    22:     0x7f715327d465 - std::sync::once::Once::call_once::hb9c2f4150c255309
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sync/once.rs:262:9
    23:     0x7f7153269a56 - lazy_static::lazy::Lazy<T>::get::h7d7d6f5f8addc658
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:30:9
    24:     0x7f7153269a56 - <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::__stability::h037f866cd6989a59
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:142:21
    25:     0x7f7153269a56 - <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::hb65f708a7f889169
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:144:17
    26:     0x7f7153261025 - bindgen::ensure_libclang_is_loaded::hccdd5926b9352c21
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2152:33
    27:     0x7f71532615fa - bindgen::Bindings::generate::h76bd14a9da93f2a1
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2211:9
    28:     0x7f715325f6a3 - bindgen::Builder::generate::hb3d6f799a7d70937
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:1478:9
    29:     0x7f71531d839a - build_script_build::main::h134bd2bc72ec9086
                                 at /croaring-rs/croaring-sys/build.rs:17:20
    30:     0x7f71531d85fb - core::ops::function::FnOnce::call_once::h18d42bc5e7b50183
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
    31:     0x7f71531d8aee - std::sys_common::backtrace::__rust_begin_short_backtrace::h510065a4f94d5d6b
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:123:18
    32:     0x7f71531d70d1 - std::rt::lang_start::{{closure}}::hc335cc61f4150ebc
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:146:18
    33:     0x7f715375e9f1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37d528e2b7386a19
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:259:13
    34:     0x7f715375e9f1 - std::panicking::try::do_call::h21f3d980e271aebe
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
    35:     0x7f715375e9f1 - std::panicking::try::h6366c75894a5ee3f
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
    36:     0x7f715375e9f1 - std::panic::catch_unwind::hbab33c6a69c714f4
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
    37:     0x7f715375e9f1 - std::rt::lang_start_internal::{{closure}}::h4a2c188522fb7f4a
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:48
    38:     0x7f715375e9f1 - std::panicking::try::do_call::h9b4b672a4b3537ad
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
    39:     0x7f715375e9f1 - std::panicking::try::h9c95acfa69428cd5
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
    40:     0x7f715375e9f1 - std::panic::catch_unwind::h137c802160173f20
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
    41:     0x7f715375e9f1 - std::rt::lang_start_internal::h89221b25a17002da
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:20
    42:     0x7f71531d70a0 - std::rt::lang_start::hc122dfcc67f5fe2f
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:145:17
    43:     0x7f71531d859c - main

```

**Comment by saulius** [comment]
Please please try version `0.7.0` of the library, `clang` should no longer be necessary with the default build. Please reopen if it's still a problem.
